// Copyright (c) 2025-present databayt
//
// Canonical CDN library for cdn.databayt.org — the helper every repo imports,
// plus the manifest types that power the /cdn showroom.
//
// Distributable: `pnpm codebase add cdn` copies this into a consuming repo's
// `src/lib/cdn.ts`. Two env vars drive it so the file is byte-identical everywhere:
//   NEXT_PUBLIC_CDN_DOMAIN    = cdn.databayt.org
//   NEXT_PUBLIC_CDN_NAMESPACE = hogwarts | souq | mkan | shifa | kun  (this repo's tier-3 segment)

const HOST = process.env.NEXT_PUBLIC_CDN_DOMAIN?.trim()
  ? `https://${process.env.NEXT_PUBLIC_CDN_DOMAIN.trim()}`
  : "https://cdn.databayt.org"
const NS = process.env.NEXT_PUBLIC_CDN_NAMESPACE?.trim() || ""

export const SHARED_NAMESPACES = ["icons", "illustrations", "animations"] as const
export type SharedNamespace = (typeof SHARED_NAMESPACES)[number]

export const PRODUCT_NAMESPACES = ["hogwarts", "souq", "mkan", "shifa", "kun"] as const

function join(...segments: string[]): string {
  const path = segments
    .map((s) => s.replace(/^\/+|\/+$/g, ""))
    .filter(Boolean)
    .join("/")
  return `${HOST}/${path}`
}

export const cdn = {
  /** Vendor mirror — flat: `cdn.vendor("anthropic", "anthropic-wordmark.svg")` */
  vendor: (brand: string, file: string) => join(brand, file),
  /** Shared design primitive: `cdn.shared("icons", "visa.svg")` */
  shared: (ns: SharedNamespace, file: string) => join(ns, file),
  /** This product's own media: `cdn.product("photos/x.jpg")` → `/<NS>/photos/x.jpg` */
  product: (path: string) => join(NS, path),
  /** Structured content: `cdn.catalog({ curriculum, grade, subject, asset })` */
  catalog: (p: { curriculum: string; grade: string; subject: string; asset: string }) =>
    join("catalog", p.curriculum, p.grade, p.subject, p.asset),
} as const

/** @deprecated raw passthrough — kept so legacy callers don't break */
export const asset = (path: string) => `${HOST}${path.startsWith("/") ? path : `/${path}`}`

// ---- Manifest (powers the /cdn showroom; generated by scripts/build-cdn-manifest.ts) ----

export type CdnTier = "vendor" | "shared" | "product" | "content"

export interface CdnAsset {
  key: string // e.g. "anthropic/anthropic-wordmark.svg"
  size?: number
  contentType?: string
  /**
   * Source/provenance tag, decoupled from the path. Lets an asset live under a
   * clean structural path (e.g. "catalog/math/banner.jpg") while staying
   * filterable by where it came from (e.g. slug "clickview"). Defaults to the
   * first path segment when omitted.
   */
  slug?: string
}

/** The provenance slug for an asset — explicit slug, else the first path segment. */
export function slugOf(asset: Pick<CdnAsset, "key" | "slug">): string {
  return asset.slug ?? asset.key.split("/")[0]
}

export interface CdnManifest {
  generatedAt: string
  source: string // "s3" | "seed (local preview)"
  bucket: string
  domain: string
  /** Optional override for where assets are served from. "/cdn" → local public/
   * preview (decoupled from the live CDN); omit → cdn.databayt.org via urlForKey. */
  urlBase?: string
  assets: CdnAsset[]
}

const SHARED_SET = new Set<string>(SHARED_NAMESPACES)
const PRODUCT_SET = new Set<string>(PRODUCT_NAMESPACES)
const CONTENT_SET = new Set<string>(["catalog", "clickview"])

/** Classify a key's tier by its first path segment. Unknown top-levels are vendors. */
export function tierOf(key: string): CdnTier {
  const top = key.split("/")[0]
  if (SHARED_SET.has(top)) return "shared"
  if (CONTENT_SET.has(top)) return "content"
  if (PRODUCT_SET.has(top)) return "product"
  return "vendor"
}

/** Full CDN URL for a manifest key. */
export function urlForKey(key: string): string {
  return `${HOST}/${key.replace(/^\/+/, "")}`
}

export function isImage(key: string): boolean {
  return /\.(svg|png|jpe?g|webp|gif|ico|avif)$/i.test(key)
}
