// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "login-01": {
      name: "login-01",
      description: "A simple login form.",
      type: "registry:template",
      registryDependencies: ["button", "card", "input", "label"],
      files: [
        {
          path: "src/components/template/login-01/page.tsx",
          type: "registry:page",
          target: "app/login/page.tsx"
        },
        {
          path: "src/components/template/login-01/components/login-form.tsx",
          type: "registry:component",
        }
      ],
      categories: ["authentication", "login"],
      component: React.lazy(() => import("@/components/template/login-01/page")),
      source: "",
      meta: {},
    },
    "hero-01": {
      name: "hero-01",
      description: "A modern hero section with call-to-action buttons.",
      type: "registry:template",
      registryDependencies: ["button"],
      files: [
        {
          path: "src/components/template/hero-01/page.tsx",
          type: "registry:page",
          target: "app/hero/page.tsx"
        }
      ],
      categories: ["hero", "marketing", "landing"],
      component: React.lazy(() => import("@/components/template/hero-01/page")),
      source: "",
      meta: {},
    },
  },
  "new-york": {
    "login-01": {
      name: "login-01",
      description: "A simple login form.",
      type: "registry:template",
      registryDependencies: ["button", "card", "input", "label"],
      files: [
        {
          path: "src/components/template/login-01/page.tsx",
          type: "registry:page",
          target: "app/login/page.tsx"
        },
        {
          path: "src/components/template/login-01/components/login-form.tsx",
          type: "registry:component",
        }
      ],
      categories: ["authentication", "login"],
      component: React.lazy(() => import("@/components/template/login-01/page")),
      source: "",
      meta: {},
    },
    "hero-01": {
      name: "hero-01",
      description: "A modern hero section with call-to-action buttons.",
      type: "registry:template",
      registryDependencies: ["button"],
      files: [
        {
          path: "src/components/template/hero-01/page.tsx",
          type: "registry:page",
          target: "app/hero/page.tsx"
        }
      ],
      categories: ["hero", "marketing", "landing"],
      component: React.lazy(() => import("@/components/template/hero-01/page")),
      source: "",
      meta: {},
    },
  },
}