import * as React from "react"
import { notFound } from "next/navigation"

// Import the registry index (this will be generated by our build script)
// @ts-ignore - Generated file
import { Index } from "@/__registry__/index"

// Define the runtime as nodejs since we might use server components
export const runtime = "nodejs"

interface ViewTemplatePageProps {
  params: Promise<{
    lang: string
    name: string
  }>
}

// Generate static params for all templates
export async function generateStaticParams() {
  const templates = []

  // Get all template names from the registry
  try {
    for (const style of Object.keys(Index)) {
      for (const name of Object.keys(Index[style])) {
        templates.push({ name })
      }
    }
  } catch (error) {
    console.error("Error generating static params:", error)
  }

  return templates
}

export default async function ViewTemplatePage({ params }: ViewTemplatePageProps) {
  const { name } = await params

  // Try to get the template from the default style first
  let template = null
  let Component = null

  try {
    // Get template metadata and component from registry
    if (Index["default"] && Index["default"][name]) {
      template = Index["default"][name]
      Component = template.component
    }

    // If not found in default, try other styles
    if (!template) {
      for (const style of Object.keys(Index)) {
        if (Index[style][name]) {
          template = Index[style][name]
          Component = template.component
          break
        }
      }
    }
  } catch (error) {
    console.error(`Error loading template ${name}:`, error)
  }

  // If template not found, return 404
  if (!template || !Component) {
    notFound()
  }

  // Apply container classes from meta if specified
  const containerClasses = template.meta?.container || ""

  return (
    <>
      <div className={containerClasses ? `bg-background ${containerClasses}` : "bg-background"}>
        <React.Suspense
          fallback={
            <div className="flex h-screen items-center justify-center">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
            </div>
          }
        >
          <Component />
        </React.Suspense>
      </div>
    </>
  )
}
