/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-template-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, Record<string, any>> = {
  "default": {
    "login-01": {
      name: "login-01",
      description: "A simple login form with email and password fields.",
      type: "registry:template",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/default/template/login-01/page.tsx",
        type: "registry:page",
        target: "app/login/page.tsx"
      }],
      component: React.lazy(async () => {
        try {
          const mod = await import("@/registry/default/template/login-01/page.tsx")
          return { default: mod.default || mod[Object.keys(mod)[0]] }
        } catch (error) {
          console.error("Error loading component:", error)
          return { default: () => null }
        }
      }),
      categories: ["authentication","login"],
      meta: {"iframeHeight":"600px","container":"flex min-h-screen items-center justify-center","mobile":"component"},
    },
    "hero-01": {
      name: "hero-01",
      description: "A modern hero section with call-to-action buttons.",
      type: "registry:template",
      registryDependencies: ["button"],
      files: [{
        path: "registry/default/template/hero-01/page.tsx",
        type: "registry:page",
        target: "app/hero/page.tsx"
      }],
      component: React.lazy(async () => {
        try {
          const mod = await import("@/registry/default/template/hero-01/page.tsx")
          return { default: mod.default || mod[Object.keys(mod)[0]] }
        } catch (error) {
          console.error("Error loading component:", error)
          return { default: () => null }
        }
      }),
      categories: ["hero","marketing","landing"],
      meta: {"iframeHeight":"700px","container":"bg-background","mobile":"component"},
    },
    "sidebar-01": {
      name: "sidebar-01",
      description: "Documentation sidebar with collapsible navigation.",
      type: "registry:template",
      registryDependencies: ["sidebar","scroll-area"],
      files: [{
        path: "registry/default/template/sidebar-01/page.tsx",
        type: "registry:page",
        target: "app/sidebar/page.tsx"
      },{
        path: "registry/default/template/sidebar-01/content.tsx",
        type: "registry:component",
        target: "components/sidebar-nav.tsx"
      },{
        path: "registry/default/template/sidebar-01/config.ts",
        type: "registry:component",
        target: "config/docs.ts"
      }],
      component: React.lazy(async () => {
        try {
          const mod = await import("@/registry/default/template/sidebar-01/page.tsx")
          return { default: mod.default || mod[Object.keys(mod)[0]] }
        } catch (error) {
          console.error("Error loading component:", error)
          return { default: () => null }
        }
      }),
      categories: ["navigation","sidebar","documentation"],
      meta: {"iframeHeight":"1000px","container":"flex min-h-screen","mobile":"screenshot"},
    },
    "header-01": {
      name: "header-01",
      description: "Responsive header with navigation and mobile menu.",
      type: "registry:template",
      registryDependencies: ["button","navigation-menu","sheet"],
      files: [{
        path: "registry/default/template/header-01/page.tsx",
        type: "registry:page",
        target: "app/header/page.tsx"
      },{
        path: "registry/default/template/header-01/content.tsx",
        type: "registry:component",
        target: "components/header.tsx"
      },{
        path: "registry/default/template/header-01/main-nav.tsx",
        type: "registry:component",
        target: "components/main-nav.tsx"
      },{
        path: "registry/default/template/header-01/mobile-nav.tsx",
        type: "registry:component",
        target: "components/mobile-nav.tsx"
      }],
      component: React.lazy(async () => {
        try {
          const mod = await import("@/registry/default/template/header-01/page.tsx")
          return { default: mod.default || mod[Object.keys(mod)[0]] }
        } catch (error) {
          console.error("Error loading component:", error)
          return { default: () => null }
        }
      }),
      categories: ["navigation","header"],
      meta: {},
    },
    "footer-01": {
      name: "footer-01",
      description: "Simple footer with links and copyright.",
      type: "registry:template",
      registryDependencies: [],
      files: [{
        path: "registry/default/template/footer-01/page.tsx",
        type: "registry:page",
        target: "app/footer/page.tsx"
      },{
        path: "registry/default/template/footer-01/content.tsx",
        type: "registry:component",
        target: "components/footer.tsx"
      }],
      component: React.lazy(async () => {
        try {
          const mod = await import("@/registry/default/template/footer-01/page.tsx")
          return { default: mod.default || mod[Object.keys(mod)[0]] }
        } catch (error) {
          console.error("Error loading component:", error)
          return { default: () => null }
        }
      }),
      categories: ["navigation","footer"],
      meta: {},
    },
  },
}